echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-HIGH TEMPERATURE BATTERY CABINET 
echo HUW-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-RRU THEFT
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo ERI-RRU THEFT
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo ERI-4G CELL DOWN
echo ERI-4G CELL DOWN
echo ERI-4G CELL DOWN
echo ERI-4G CELL DOWN
echo ERI-4G CELL DOWN
echo ERI-4G CELL DOWN
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo HUW-DC VOLTAGE LOW
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW- SMOKE ALARM 
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW- SMOKE ALARM 
echo HUW- SMOKE ALARM 
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW- SMOKE ALARM 
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-AC MAINS FAILURE
echo ERI-RRU THEFT
echo HUW- SMOKE ALARM 
echo HUW-DC VOLTAGE LOW
echo ERI-AC MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-RRU THEFT
echo HUW-RRU THEFT
echo HUW-RRU THEFT
echo HUW-DC VOLTAGE LOW
echo ERI-DC LOW VOLTAGE
echo HUW-MAINS FAILURE
echo HUW-RRU THEFT
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo HUW-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-RRU THEFT
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo HUW-MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-HIGH TEMPERATURE
echo HUW- SMOKE ALARM 
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo HUW-MAINS FAILURE
echo HUW-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-DC LOW VOLTAGE
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo HUW-MAINS FAILURE
echo HUW-HIGH TEMPERATURE BATTERY CABINET 
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo ERI-SMOKE ALARM
echo HUW-2G CELL DOWN
echo ERI-SMOKE ALARM
echo HUW-MAINS FAILURE
echo ERI-RRU THEFT
echo ERI-RRU THEFT
echo ERI-DC LOW VOLTAGE
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo HUW-DC VOLTAGE LOW
echo HUW-HIGH TEMPERATURE
echo HUW-DC VOLTAGE LOW
echo HUW-RRU THEFT
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-AC MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-HIGH TEMPERATURE
echo HUW-HIGH TEMPERATURE BATTERY CABINET 
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo HUW-MAINS FAILURE
echo HUW-RRU THEFT
echo HUW-RRU THEFT
echo HUW-RRU THEFT
echo HUW-RRU THEFT
echo HUW-RRU THEFT
echo HUW-RRU THEFT
echo HUW-DC VOLTAGE LOW
echo ERI-AC MAINS FAILURE
echo HUW-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-4G CELL DOWN
echo ERI-4G CELL DOWN
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo HUW-MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo ERI-4G CELL DOWN
echo ERI-4G CELL DOWN
echo ERI-4G CELL DOWN
echo ERI-DC LOW VOLTAGE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo ERI-DC LOW VOLTAGE
echo ERI-DC LOW VOLTAGE
echo ERI-DC LOW VOLTAGE
echo HUW-RRU THEFT
echo HUW-RRU THEFT
echo HUW-RRU THEFT
echo ERI-SMOKE ALARM
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-DC LOW VOLTAGE
echo ERI-DC LOW VOLTAGE
echo ERI-SMOKE ALARM
echo ERI-4G SITE DOWN
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo ERI-DC LOW VOLTAGE
echo HUW-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-DC LOW VOLTAGE
echo ERI-SMOKE ALARM
echo ERI-DC LOW VOLTAGE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-2G CELL DOWN
echo ERI-2G CELL DOWN
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo HUW- SMOKE ALARM 
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-RRU THEFT
echo HUW-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo HUW-HIGH TEMPERATURE BATTERY CABINET 
echo ERI-SMOKE ALARM
echo HUW-DC VOLTAGE LOW
echo HUW-HIGH TEMPERATURE
echo HUW- SMOKE ALARM 
echo ERI-RRU THEFT
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo ERI-SMOKE ALARM
echo HUW-DC VOLTAGE LOW
echo ERI-AC MAINS FAILURE
echo HUW- SMOKE ALARM 
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-RRU THEFT
echo ERI-RRU THEFT
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-RRU THEFT
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-HIGH TEMPERATURE
echo HUW- SMOKE ALARM 
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo ERI-SMOKE ALARM
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW- SMOKE ALARM 
echo ERI-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo HUW-MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-RRU THEFT
echo ERI-RRU THEFT
echo ERI-RRU THEFT
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-RRU THEFT
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo HUW-MAINS FAILURE
echo HUW-RRU THEFT
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo ERI-RRU THEFT
echo ERI-RRU THEFT
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-DC LOW VOLTAGE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-DC LOW VOLTAGE
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo HUW-HIGH TEMPERATURE
echo HUW- SMOKE ALARM 
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo HUW-HIGH TEMPERATURE BATTERY CABINET 
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-DC LOW VOLTAGE
echo ERI-SMOKE ALARM
echo ERI-DC LOW VOLTAGE
echo ERI-DC LOW VOLTAGE
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-HIGH TEMPERATURE BATTERY CABINET 
echo HUW-RRU THEFT
echo HUW-RRU THEFT
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW- SMOKE ALARM 
echo HUW-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo ERI-DC LOW VOLTAGE
echo HUW-RRU THEFT
echo HUW- SMOKE ALARM 
echo HUW-RRU THEFT
echo HUW-MAINS FAILURE
echo HUW- SMOKE ALARM 
echo HUW-DC VOLTAGE LOW
echo ERI-DC LOW VOLTAGE
echo ERI-DC LOW VOLTAGE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo ERI-SMOKE ALARM
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo ERI-DC LOW VOLTAGE
echo HUW-MAINS FAILURE
echo ERI-HIGH TEMPERATURE
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo HUW-MAINS FAILURE
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW-MAINS FAILURE
echo ERI-SMOKE ALARM
echo HUW-HIGH TEMPERATURE BATTERY CABINET 
echo HUW-MAINS FAILURE
echo HUW-DC VOLTAGE LOW
echo HUW- SMOKE ALARM 
echo ERI-SMOKE ALARM
echo ERI-SMOKE ALARM
echo HUW-MAINS FAILURE
echo ERI-SMOKE ALARM
echo ERI-RRU THEFT
echo ERI-DC LOW VOLTAGE
echo ERI-DC LOW VOLTAGE
echo ERI-HIGH TEMPERATURE
echo ERI-HIGH TEMPERATURE
echo HUW-DC VOLTAGE LOW
echo HUW-HIGH TEMPERATURE
echo ERI-AC MAINS FAILURE
echo ERI-DC LOW VOLTAGE
echo HUW-MAINS FAILURE
echo ERI-AC MAINS FAILURE
echo ERI-RRU THEFT
echo ERI-RRU THEFT
echo ERI-RRU THEFT
